## Soru 1 – Liste Metotları

### Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
### notlar = [85, 92, 76, 92, 100, 76, 85, 92]
#### • Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
#### • En yüksek ve en düşük notu bulun.
#### • Notları küçükten büyüğe sıralayın.

In [24]:
# Öğrenci notları listesi
notlar = [85, 92, 76, 92, 100, 76, 85, 92] 

# Tekrar eden notları silip benzersiz bir liste oluşturalım 
benzersiz_notlar = list(set(notlar))
print("Yeni öğrenci not listesi:", benzersiz_notlar, "\n")

# En yüksek ve en düşük notu bulalım
en_yuksek = max(benzersiz_notlar)
en_dusuk = min(benzersiz_notlar)
print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk, "\n")

# Notları küçükten büyüğe doğru sıralayalım 
sirali_notlar = sorted(benzersiz_notlar)
print("Küçükten büyüğe sıralı notlar:", sirali_notlar)

Yeni öğrenci not listesi: [100, 92, 85, 76] 

En yüksek not: 100
En düşük not: 76 

Küçükten büyüğe sıralı notlar: [76, 85, 92, 100]


## Soru 2 – Sayılar

### Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.

In [13]:
sayi = 370

# sayıyı stringe yazı tipine çeviriyoruz
basamaklar = str(sayi)
toplam = sum(int(digit)**3 for digit in basamaklar)  # her basamağın küpünü alıp topluyoruz

if toplam == sayi:
    print(sayi, "--->", "Bir Armstrong Sayısıdır.")
else:
    print(sayi, "--->", "Bir Armstrong Sayısı Değildir.")


370 ---> Bir Armstrong Sayısıdır.


## Soru 3 – Kümeler

### Aşağıdaki iki küme verilmiştir:
### A = {"Python", "R", "SQL", "Java"}
### B = {"C++", "Python", "JavaScript", "SQL"}
#### • Ortak dilleri bulun.
#### • Sadece A’da olan dilleri listeleyin.
#### • İki kümenin birleşimini alfabetik olarak yazdırın.

In [21]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# Ortak dilleri buluyoruz 
ortak = A.intersection(B)
print("Ortak diller:", ortak)

# Sadece A’da olan dilleri listeliyoruz 
sadece_A = A.difference(B)
print("Sadece A'da olan diller:", sadece_A)

# İki kümeyi birleştirip alfabetik sırayla listeliyoruz
birlesim = sorted(A.union(B))
print("Birleşim (alfabetik):", birlesim)

Ortak diller: {'SQL', 'Python'}
Sadece A'da olan diller: {'Java', 'R'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


## Soru 4 – Modüller

### • random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
### • Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [27]:
import numpy as np

sayilar = np.random.randint(1, 101, 10)
print("Rastgele sayılar:", sayilar)
print("Ortalama:", np.mean(sayilar))
print("Standart sapma:", np.std(sayilar, ddof=1))

Rastgele sayılar: [58 32 33 93 84 42 19 25 56 52]
Ortalama: 49.4
Standart sapma: 24.42312201355283


## Soru 5 – Fonksiyonlar

### kelime_sayacı(metin) adında bir fonksiyon yazın. Fonksiyon verilen metindeki:
#### • toplam kelime sayısını
#### • en uzun kelimeyi
#### • en sık geçen kelimeyi döndürsün.

In [46]:
def kelime_sayaci(metin):
    
# Metni kelimelere ayırıyoruz
    kelimeler = metin.split()
    
# Toplam kelime sayısını buluyoruz
    toplam = len(kelimeler)
    
# En uzun kelimeyi buluyoruz
    en_uzun = max(kelimeler, key=len)
    
# En çok geçen kelimeyi buluyoruz
    en_cok = max(set(kelimeler), key=kelimeler.count)
    
    return toplam, en_uzun, en_cok


metin = "veri temizlemek veri analizi için şarttır."
sonuc = kelime_sayaci(metin)
print("Toplam kelime sayısı:", sonuc[0])
print("En uzun kelime:", sonuc[1])
print("En çok geçen kelime:", sonuc[2])


Toplam kelime sayısı: 6
En uzun kelime: temizlemek
En çok geçen kelime: veri


## Soru 6 – Gömülü Fonksiyonlar

### Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
### sayilar = [5, 12, 7, 18, 24, 3, 16]
#### • Sadece çift sayıları filtreleyin.
#### • Bu sayıların karelerini bulun.
#### • Karelerini azalan sırada sıralayın.

In [4]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

# Çift sayıları filtreleyelim
ciftler = filter(lambda x: x % 2 == 0, sayilar)

# Karelerini bulalım
kareler = map(lambda x: x**2, ciftler)

# Azalan sırada sıralayalım
sirali_kareler = sorted(kareler, reverse=True)

print("Sonuç:", sirali_kareler)

Sonuç: [576, 324, 256, 144]


## Soru 7 – Lambda İfadeleri

### Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
### kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

In [9]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

# Kelime uzunluklarına göre sıralayalım
sirali = sorted(kelimeler, key=lambda x: len(x))

print("Sıralı liste:", sirali)

Sıralı liste: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


## Soru 8 – Metodlar

### Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon yazın.

In [15]:
import re

def rakam_toplami(metin):
    sayilar = re.findall(r"\d+", metin)  
    return sum(map(int, sayilar))

print(rakam_toplami("abc45km21s"))

66


## Soru 9 – Numpy 1

### 10 elemanlı bir numpy dizisi oluşturun.
#### • Elemanlar 0–50 arasında rastgele sayılar olsun.
#### • Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [20]:
import numpy as np

# 10 elemanlı, 0–50 arasında rastgele sayılar üretelim
dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)

# Ortalama
ortalama = np.mean(dizi)
print("Ortalama:", ortalama)

# Standart sapma
std_sapma = np.std(dizi)
print("Standart sapma:", std_sapma)

# En büyük değer
en_buyuk = np.max(dizi)
print("En büyük değer:", en_buyuk)

Dizi: [50 28 27 18  1 17 26 43  9 17]
Ortalama: 23.6
Standart sapma: 13.972830779766854
En büyük değer: 50


## Soru 10 – Numpy 2

### 5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
#### • Her sütunun ortalamasını bulun.
#### • 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [24]:
import numpy as np

# 5x5 boyutunda 0-1 arasında rastgele değerlerden oluşan matris oluşturalım
matris = np.random.rand(5, 5)
print("Orijinal matris:\n", matris)

# Her sütunun ortalamasını bulalım
sutun_ortalari = np.mean(matris, axis=0)
print("Sütun ortalamaları:", sutun_ortalari)

# Binary matris oluşturalım
binary_matris = np.where(matris > 0.5, 1, 0)
print("Binary matris:\n", binary_matris)

Orijinal matris:
 [[0.04045501 0.66600385 0.89419283 0.60414544 0.37382287]
 [0.47780169 0.73306437 0.497339   0.58073256 0.94015482]
 [0.90368932 0.70194489 0.06934177 0.51133859 0.38291068]
 [0.73022561 0.45014107 0.22823337 0.23044346 0.63800077]
 [0.44773626 0.67456701 0.61809214 0.51050724 0.59049951]]
Sütun ortalamaları: [0.51998158 0.64514424 0.46143982 0.48743346 0.58507773]
Binary matris:
 [[0 1 1 1 0]
 [0 1 0 1 1]
 [1 1 0 1 0]
 [1 0 0 0 1]
 [0 1 1 1 1]]
